//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the robot_vision package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __robot_vision__ROBOT_VISION_PARAMSCONFIG_H__
#define __robot_vision__ROBOT_VISION_PARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace robot_vision
{
  class robot_vision_paramsConfigStatics;

  class robot_vision_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(robot_vision_paramsConfig &config, const robot_vision_paramsConfig &max, const robot_vision_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const robot_vision_paramsConfig &config1, const robot_vision_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, robot_vision_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const robot_vision_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, robot_vision_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const robot_vision_paramsConfig &config) const = 0;
      virtual void getValue(const robot_vision_paramsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T robot_vision_paramsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T robot_vision_paramsConfig::* field;

      virtual void clamp(robot_vision_paramsConfig &config, const robot_vision_paramsConfig &max, const robot_vision_paramsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const robot_vision_paramsConfig &config1, const robot_vision_paramsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, robot_vision_paramsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const robot_vision_paramsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, robot_vision_paramsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const robot_vision_paramsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const robot_vision_paramsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, robot_vision_paramsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, robot_vision_paramsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<robot_vision_paramsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(robot_vision_paramsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("voxelLeafSize"==(*_i)->name){voxelLeafSize = boost::any_cast<double>(val);}
        if("removePlaneIterations"==(*_i)->name){removePlaneIterations = boost::any_cast<int>(val);}
        if("distanceThreshold"==(*_i)->name){distanceThreshold = boost::any_cast<double>(val);}
        if("PercentageCloud"==(*_i)->name){PercentageCloud = boost::any_cast<double>(val);}
        if("tolerance"==(*_i)->name){tolerance = boost::any_cast<double>(val);}
        if("minClustersSize"==(*_i)->name){minClustersSize = boost::any_cast<int>(val);}
        if("maxClustersSize"==(*_i)->name){maxClustersSize = boost::any_cast<int>(val);}
        if("size"==(*_i)->name){size = boost::any_cast<int>(val);}
      }
    }

    double voxelLeafSize;
int removePlaneIterations;
double distanceThreshold;
double PercentageCloud;
double tolerance;
int minClustersSize;
int maxClustersSize;
int size;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double voxelLeafSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int removePlaneIterations;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distanceThreshold;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double PercentageCloud;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double tolerance;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minClustersSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int maxClustersSize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int size;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("robot_vision_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const robot_vision_paramsConfig &__max__ = __getMax__();
      const robot_vision_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const robot_vision_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const robot_vision_paramsConfig &__getDefault__();
    static const robot_vision_paramsConfig &__getMax__();
    static const robot_vision_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const robot_vision_paramsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void robot_vision_paramsConfig::ParamDescription<std::string>::clamp(robot_vision_paramsConfig &config, const robot_vision_paramsConfig &max, const robot_vision_paramsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class robot_vision_paramsConfigStatics
  {
    friend class robot_vision_paramsConfig;

    robot_vision_paramsConfigStatics()
    {
robot_vision_paramsConfig::GroupDescription<robot_vision_paramsConfig::DEFAULT, robot_vision_paramsConfig> Default("Default", "", 0, 0, true, &robot_vision_paramsConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.voxelLeafSize = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.voxelLeafSize = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.voxelLeafSize = 0.005;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("voxelLeafSize", "double", 0, "set leaf size for Voxel grid filter", "", &robot_vision_paramsConfig::voxelLeafSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("voxelLeafSize", "double", 0, "set leaf size for Voxel grid filter", "", &robot_vision_paramsConfig::voxelLeafSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.removePlaneIterations = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.removePlaneIterations = 500;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.removePlaneIterations = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("removePlaneIterations", "int", 0, "max iterations", "", &robot_vision_paramsConfig::removePlaneIterations)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("removePlaneIterations", "int", 0, "max iterations", "", &robot_vision_paramsConfig::removePlaneIterations)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distanceThreshold = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distanceThreshold = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distanceThreshold = 0.02;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("distanceThreshold", "double", 0, "distance Threshold", "", &robot_vision_paramsConfig::distanceThreshold)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("distanceThreshold", "double", 0, "distance Threshold", "", &robot_vision_paramsConfig::distanceThreshold)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.PercentageCloud = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.PercentageCloud = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.PercentageCloud = 40.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("PercentageCloud", "double", 0, "percentage Point Cloud", "", &robot_vision_paramsConfig::PercentageCloud)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("PercentageCloud", "double", 0, "percentage Point Cloud", "", &robot_vision_paramsConfig::PercentageCloud)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tolerance = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tolerance = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tolerance = 0.03;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("tolerance", "double", 0, "Cluster tolerance", "", &robot_vision_paramsConfig::tolerance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<double>("tolerance", "double", 0, "Cluster tolerance", "", &robot_vision_paramsConfig::tolerance)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minClustersSize = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minClustersSize = 50000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minClustersSize = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("minClustersSize", "int", 0, "min Cluster Size", "", &robot_vision_paramsConfig::minClustersSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("minClustersSize", "int", 0, "min Cluster Size", "", &robot_vision_paramsConfig::minClustersSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxClustersSize = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxClustersSize = 50000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxClustersSize = 25000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("maxClustersSize", "int", 0, "max Cluster Size", "", &robot_vision_paramsConfig::maxClustersSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("maxClustersSize", "int", 0, "max Cluster Size", "", &robot_vision_paramsConfig::maxClustersSize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.size = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.size = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.size = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("size", "int", 0, "A size parameter which is edited via an enum", "{'enum': [{'name': 'Small', 'type': 'int', 'value': 0, 'srcline': 31, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'A small constant', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Medium', 'type': 'int', 'value': 1, 'srcline': 32, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'A medium constant', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Large', 'type': 'int', 'value': 2, 'srcline': 33, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'A large constant', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExtraLarge', 'type': 'int', 'value': 3, 'srcline': 34, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'An extra large constant', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set size'}", &robot_vision_paramsConfig::size)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(robot_vision_paramsConfig::AbstractParamDescriptionConstPtr(new robot_vision_paramsConfig::ParamDescription<int>("size", "int", 0, "A size parameter which is edited via an enum", "{'enum': [{'name': 'Small', 'type': 'int', 'value': 0, 'srcline': 31, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'A small constant', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Medium', 'type': 'int', 'value': 1, 'srcline': 32, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'A medium constant', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Large', 'type': 'int', 'value': 2, 'srcline': 33, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'A large constant', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExtraLarge', 'type': 'int', 'value': 3, 'srcline': 34, 'srcfile': '/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg', 'description': 'An extra large constant', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set size'}", &robot_vision_paramsConfig::size)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(robot_vision_paramsConfig::AbstractGroupDescriptionConstPtr(new robot_vision_paramsConfig::GroupDescription<robot_vision_paramsConfig::DEFAULT, robot_vision_paramsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<robot_vision_paramsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<robot_vision_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<robot_vision_paramsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    robot_vision_paramsConfig __max__;
    robot_vision_paramsConfig __min__;
    robot_vision_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const robot_vision_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static robot_vision_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &robot_vision_paramsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const robot_vision_paramsConfig &robot_vision_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const robot_vision_paramsConfig &robot_vision_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const robot_vision_paramsConfig &robot_vision_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<robot_vision_paramsConfig::AbstractParamDescriptionConstPtr> &robot_vision_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<robot_vision_paramsConfig::AbstractGroupDescriptionConstPtr> &robot_vision_paramsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const robot_vision_paramsConfigStatics *robot_vision_paramsConfig::__get_statics__()
  {
    const static robot_vision_paramsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = robot_vision_paramsConfigStatics::get_instance();

    return statics;
  }

//#line 31 "/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg"
      const int robot_vision_params_Small = 0;
//#line 32 "/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg"
      const int robot_vision_params_Medium = 1;
//#line 33 "/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg"
      const int robot_vision_params_Large = 2;
//#line 34 "/home/robo/ros/src/cnn_pointcloud/cfg/robot_vision_params.cfg"
      const int robot_vision_params_ExtraLarge = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ROBOT_VISION_PARAMSRECONFIGURATOR_H__
