set(_CATKIN_CURRENT_PACKAGE "segmentation1")
set(segmentation1_VERSION "0.0.0")
set(segmentation1_MAINTAINER "robo <robo@todo.todo>")
set(segmentation1_PACKAGE_FORMAT "2")
set(segmentation1_BUILD_DEPENDS )
set(segmentation1_BUILD_EXPORT_DEPENDS )
set(segmentation1_BUILDTOOL_DEPENDS "catkin")
set(segmentation1_BUILDTOOL_EXPORT_DEPENDS )
set(segmentation1_EXEC_DEPENDS )
set(segmentation1_RUN_DEPENDS )
set(segmentation1_TEST_DEPENDS )
set(segmentation1_DOC_DEPENDS )
set(segmentation1_URL_WEBSITE "")
set(segmentation1_URL_BUGTRACKER "")
set(segmentation1_URL_REPOSITORY "")
set(segmentation1_DEPRECATED "")